### ISSUE TITLE
Important Changes (German)

### ISSUE THREAD

**Issue by NiKrause** [Doichain/bounties#1]
- Es gibt keinen User-Namen sondern nur E-Mail Adresse. Auf der Übersichtsseite (ohne vorherigem Login) wird bei "blocked by" nichts angezeigt. Wenn man angemeldet ist, wird die E-Mail Adresse angezeigt. Das ist ein wenig doof. Ich hätte zum Beispiel keine Lust, dass meine E-Mail öffnetlich einsehbar ist. Zu mal Bots sie crawlen können und ich dann mit Spammails rechnen kann. Daher wäre es schön, wenn es einen Usernamen gibt. Den man stattdessen veröffentlichen kann.

- Bei der Registrierung wird eine E-Mail versendet, die noch von deiner Domain verschickt wird. Hier sollten wir auf doichain.org umstellen und idealerweise über smtp-relay (zertifizierte IP-Adresse von sendeffect) versenden.

- Der Inhalt der Aktivierungsmail steht denke ich noch aus? Da sollte evtl. ein wenig mehr drin stehen und hübscher aussehen. Impressum sollte auch rein.

- Beim Bestätigen wird man auf die subdomain bounties.doichain.org weitergeleitet. Hier sollte die Zielseite doichain.org/bounties sein.

- Die Bestätigung "Email verified. You are now logged in as...", nach der Aktivierung kann man leicht übersehen. Hat man hier die Möglichkeit diese anders in die Seite zu initegrieren?

- Bei Priority: Hier wird ein Zahlenwert verwendet (1-3). Ich gehe davon aus, dass 3 die höchste Prio ist? Das könnte man so oder so verstehen. Wäre es daher eindeutiger, wenn wir Wörter verwenden? High, middle und low?

- Zur Info: Ich habe für Testzwecke "Manage Telegram Channel" blockiert.

**Comment by sines99** [comment]
kann geschlossen werden

**Comment by NiKrause** [comment]
ist alles erledigt?
